/* The twelve questions. Edit text here; see SETUP.md for the field guide.
   answer: [true]/[false] for true/false; for multi, option positions counting from 0. */
window.QUESTIONS = [
{ id:"q1", short:"Pulse during compressions = ROSC?",
  stem:"A palpable femoral pulse during chest compressions means the patient has achieved ROSC.",
  type:"tf", answer:[false],
  why:["Palpable pulses during active compressions are common, felt in 52% of patients in one study. Compressions themselves create arterial and venous pulsatility, and a pulsation doesn't prove forward arterial flow, let alone spontaneous circulation.",
       "RECOVER distinguishes a pulse occurring with compressions from a spontaneous pulse independent of them. That said, palpable pulses during compressions are associated with higher odds of sustained ROSC (OR 4.36 [1.85–10.30])."],
  takeaway:"A pulse during compressions tells you blood is moving and may be a good prognostic sign. It doesn't tell you the heart is moving it on its own." },

{ id:"q2", short:"ETCO₂ of 18 mmHg = compressions optimized?",
  stem:"An ETCO₂ of 18 mmHg indicates that chest compressions have been optimized.",
  type:"tf", answer:[false],
  why:["RECOVER recommends maximizing ETCO₂ to no less than 18 mmHg. That number came from veterinary data identifying a useful prognostic cutoff, not from evidence that 18 is the ideal treatment endpoint.",
       "With ventilation held constant, ETCO₂ during CPR largely reflects pulmonary blood flow, so it tracks the circulation you're generating. Across studies, animals achieving ROSC generally had higher ETCO₂."],
  takeaway:"18 mmHg is the floor, not the finish line." },

{ id:"q3", short:"Differentials for a flat-line ETCO₂ of 0",
  stem:"Which of these are differential diagnoses for an ETCO₂ of 0 with a flat-line waveform during chest compressions?",
  type:"multi",
  options:["Esophageal intubation","Poor-quality chest compressions","A respiratory rate of 20 breaths per minute","An uninflated ETT cuff"],
  answer:[0,3],
  why:["A true flat-line zero means no alveolar gas is reaching the capnograph. Esophageal intubation sends gas to the stomach. An uninflated cuff can't hold a seal against the large pressure swings of ongoing compressions, so there's no alveolar ventilation at all. It's the same reason bag-mask or mouth-to-nose ventilation doesn't work during compressions.",
       "Poor-quality compressions lower ETCO₂ but leave a low, present waveform. A respiratory rate of 20 changes ETCO₂ without flatlining it."],
  takeaway:"A flat zero points to the airway first: check ETT position, cuff seal, and the circuit." },

{ id:"q4", short:"Fluid boluses often harmful during CPR?",
  stem:"In many patients, fluid boluses are likely to be harmful during CPR.",
  type:"tf", answer:[true],
  why:["Coronary perfusion pressure is aortic diastolic pressure minus right atrial pressure. In a normovolemic patient, a bolus raises right atrial pressure and shrinks the very gradient that drives ROSC.",
       "Boluses make sense when hypovolemia contributed to the arrest, not as a routine measure."],
  takeaway:"\u201CFluids help\u201D is a sticky instinct. During CPR in a normovolemic patient, they can hurt." },

{ id:"q5", short:"VF / pVT: electrical but no mechanical activity?",
  stem:"In patients with VF and pulseless VT, there is electrical but not mechanical activity in the heart.",
  type:"tf", answer:[false],
  why:["There is mechanical activity in VF and pulseless VT. It's disorganized and doesn't produce effective output, but it's there. That's different from asystole, with no electrical or mechanical activity, and classic PEA.",
       "That distinction is why these are the only arrest rhythms where defibrillation makes sense: the shock stops that activity so the heart's own pacemakers can take over."],
  takeaway:"Shockable rhythms have activity to stop. That's the whole point of the shock." },

{ id:"q6", short:"Defibrillation stops the heart’s activity?",
  stem:"The goal of electrical defibrillation is to stop the heart\u2019s electrical and mechanical activity.",
  type:"tf", answer:[true],
  why:["Defibrillation depolarizes the myocardium all at once, terminating the chaotic activity of a shockable rhythm. With that activity stopped, the natural pacemakers get a chance to re-establish a coordinated rhythm.",
       "It doesn't jump-start a stopped heart, which is why it only makes sense for VF and pulseless VT."],
  takeaway:"Defibrillation is a reset button that stops activity, not a spark that starts it." },

{ id:"q7", short:"Epinephrine before the first rhythm diagnosis?",
  stem:"Because shockable arrest rhythms are uncommon in dogs and cats, it\u2019s reasonable to give epinephrine during CPR before the first rhythm diagnosis.",
  type:"tf", answer:[false],
  why:["If the rhythm turns out to be shockable, epinephrine can worsen the discoordinated activity of the heart and make it less responsive to defibrillation.",
       "Shockable rhythms are also more common than most people assume. You'll see the numbers in question 11."],
  takeaway:"Get a rhythm diagnosis before reaching for epinephrine." },

{ id:"q8", short:"Anesthetic asystole: epinephrine before reversals?",
  stem:"In dogs and cats that develop asystole while monitored by ECG under anesthesia, epinephrine should be prioritized over reversal drugs during the first cycle of chest compressions.",
  type:"tf", answer:[true],
  why:["Reversal drugs won't restart an arrested heart. Epinephrine's peripheral vasoconstriction raises coronary perfusion and is more likely to help get the heart beating again.",
       "Reversing an anesthetic contributor still matters as a reversible cause, but it shouldn't delay epinephrine."],
  takeaway:"In monitored anesthetic asystole, epinephrine comes first. Reversals aren't a substitute for it." },

{ id:"q9", short:"Team leader helps only inexperienced teams?",
  stem:"A clearly defined team leader can improve CPR quality and outcomes in inexperienced or ad hoc teams, but not in experienced teams that regularly work together.",
  type:"tf", answer:[false],
  why:["A clearly defined leader improves CPR quality and outcomes across teams. The benefit isn't limited to inexperienced or ad hoc groups.",
       "Sources: Kuzovlev et al., Resuscitation 2021;160:126–139. Hoff et al., J Trauma 1997;43(5):772–777."],
  takeaway:"Leadership and role clarity help experienced teams too." },

{ id:"q10", short:"Refractory = no response to the first shock?",
  stem:"A shockable arrest rhythm is defined as refractory if it does not respond to the first shock.",
  type:"tf", answer:[true],
  why:["By definition, a shockable rhythm is refractory if it doesn't respond to the first shock.",
       "The catch: we don't look at the ECG right after defibrillating. Compressions resume immediately and run a full 2-minute cycle before the next rhythm check. So although refractoriness is defined by the first shock, you can't confirm it until that second rhythm check."],
  think:["Why don\u2019t we look at the ECG right after we shock?","When should you consider the additional drugs in the refractory box, and in what order?"],
  takeaway:"Refractory means no response to the first shock, but you won\u2019t know it until the second rhythm check." },

{ id:"q11", short:"Registry: shockable rhythms in under 5%?",
  stem:"According to the RECOVER CPR registry (627 dogs and cats), shockable arrest rhythms occur at some point during CPR in less than 5% of patients.",
  type:"tf", answer:[false],
  why:["Initial shockable rhythms alone are rare: 4.4% of dogs and 4.7% of cats. But many animals that start non-shockable convert later. Counting both, 19% of dogs and 9% of cats had a shockable rhythm at some point.",
       "Combined, that's 102 of 627, about one in six. Conversion is especially common in animals that start non-shockable and receive epinephrine."],
  takeaway:"Shockable rhythms are more common than most people think, so plan for them." },

{ id:"q12", short:"Low-quality evidence because none in any species?",
  stem:"The majority of RECOVER CPR guideline recommendations are based on low-quality evidence. This is because there is so little evidence in any species to answer the questions.",
  type:"tf", answer:[false],
  why:["The first half is true: most recommendations carry a low-quality grade. The reason is wrong. The grade mostly reflects sparse dog and cat data, while many recommendations are well supported by other species, especially humans.",
       "GRADE methodology downgrades for indirectness, so an excellent human trial will often be graded low quality for veterinary use."],
  takeaway:"A low-quality grade doesn\u2019t mean no evidence. It often means strong human evidence, downgraded for indirectness." }
];
